### ISSUE TITLE
Make managing keyboard firmware here simple

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/keyboards#1]
I rarely change my keyboard's programming. So, each time I do, I basically start from scratch learning how. Eventually I just go back to QMK Configurator, and maybe update my keymap and notes in this repo.

I think QMK Configurator is an excellent way to go. I'd also like to be able to edit a text file, rebuild, and flash - without having to use the Configurator.

```[tasklist]
### Tasks
- [ ] Learn how qmk firmware wants to be made (without Configurator)
- [ ] How do others meet this need?<br />What's https://github.com/lee-dohm/keyboard-firmware do?<br />Find 2-3 other examples and see how they go<br />Check out Actions published [in GitHub Marketplace](https://github.com/marketplace?category=&type=&verification=&query=qmk)
- [ ] Document pushing .hex to keyboard (from GUI? or shell?)
- [ ] Outline workflow: Build .hex for a keyboard and default keymap
- [ ] Outline workflow: Build .hex for a keyboard and custom keymap
- [ ] Decide whether to use keymap .json, .c, or both
- [ ] Document local development and testing
```
